# Generated by Django 4.1 on 2022-09-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remera',
            new_name='Remeras',
        ),
    ]
